'use client'

import { useState } from 'react'
import { ArrowRight, ChevronDown, CircleCheck, FileText, HandHeart, Lightbulb, Menu, ShieldCheck, Sparkles, Users, X } from 'lucide-react'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260810_202733156_iOS-Ctc7Z9PhUB4AJ83OcoEhjp9JP2lc4s.png'
const audiences = [
  ['Parents and carers', 'Make sense of what you are seeing and find practical next steps.', HandHeart],
  ['Schools and SENCOs', 'Turn observations into clear evidence and consistent support.', Users],
  ['Professionals', 'Bring needs-led thinking into early conversations and planning.', ShieldCheck],
] as const
const pathway = [
  ['Notice', 'Start with what is happening', 'Capture observations, patterns and context without labels or assumptions.', FileText],
  ['Understand', 'Find the unmet need', 'Look across regulation, sensory processing, communication, learning and daily life.', Lightbulb],
  ['Act', 'Build a better response', 'Share a focused summary and agree small, meaningful adjustments around the child.', CircleCheck],
] as const
const faqs = [
  ['Does NeuroPathway diagnose?', 'No. NeuroPathway helps people recognise and describe observed needs. Diagnosis can only be made by qualified clinicians.'],
  ['Who can use it?', 'Parents, carers, teachers, SENCOs, NHS staff and professionals can use it to organise observations into clearer conversations.'],
  ['What if there is an immediate safety concern?', 'If there is self-harm, suicide risk, abuse, neglect or immediate danger, seek urgent help through your local safeguarding or emergency pathway.'],
]

export function CicHome() {
  const [menu, setMenu] = useState(false)
  const [faq, setFaq] = useState<number | null>(null)
  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border/70 bg-background/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10"><a href="#top" className="flex items-center gap-3"><img src={logoUrl} alt="Social Innovation CIC logo" className="h-14 w-14 rounded-full object-cover" /><span className="hidden max-w-28 text-xs font-semibold uppercase leading-tight tracking-[.18em] text-navy sm:block">Social Innovation CIC</span></a><nav className="hidden items-center gap-8 text-sm font-semibold text-muted-foreground md:flex"><a href="#why">Why this matters</a><a href="#pathway">The pathway</a><a href="#about">About us</a><a href="#contact" className="rounded-full bg-navy px-5 py-3 text-white">Start a conversation</a></nav><button className="rounded-full p-2 text-navy md:hidden" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close menu' : 'Open menu'}>{menu ? <X size={22} /> : <Menu size={22} />}</button></div>{menu && <nav className="flex flex-col gap-4 border-t border-border px-6 py-5 text-sm font-semibold md:hidden"><a href="#why">Why this matters</a><a href="#pathway">The pathway</a><a href="#about">About us</a><a href="#contact" className="text-teal">Start a conversation</a></nav>}</header>
    <section id="top" className="mx-auto grid max-w-7xl items-center gap-10 px-6 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-28 lg:pt-24"><div><p className="mb-6 flex items-center gap-3 text-xs font-bold uppercase tracking-[.24em] text-teal"><span className="h-px w-10 bg-gold" />Prevention is the cure</p><h1 className="max-w-3xl text-balance font-serif text-5xl leading-[1.03] tracking-[-.04em] text-navy sm:text-6xl lg:text-7xl">Every child deserves <em className="text-gold">early understanding.</em></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">We help the people around children notice patterns, describe unmet needs and take clear, supportive next steps — before small struggles become bigger barriers.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#pathway" className="inline-flex items-center justify-center gap-2 rounded-full bg-navy px-6 py-3.5 font-semibold text-white">Explore the pathway <ArrowRight size={17} /></a><a href="#about" className="inline-flex items-center justify-center rounded-full border border-navy/20 px-6 py-3.5 font-semibold text-navy">How we work</a></div><div className="mt-12 flex flex-wrap gap-8 text-sm font-semibold text-muted-foreground"><span className="flex items-center gap-2"><CircleCheck size={16} className="text-teal" />Needs before labels</span><span className="flex items-center gap-2"><CircleCheck size={16} className="text-teal" />Evidence focused</span></div></div><div className="relative flex min-h-[380px] items-center justify-center"><div className="absolute h-72 w-72 rounded-full bg-teal/10 blur-3xl" /><div className="relative rounded-full border border-gold/30 bg-white p-4 shadow-2xl sm:p-7"><img src={logoUrl} alt="Social Innovation CIC emblem" className="h-72 w-72 rounded-full object-cover sm:h-[390px] sm:w-[390px] lg:h-[450px] lg:w-[450px]" /></div><div className="absolute bottom-2 left-0 max-w-48 rounded-2xl border border-border bg-white p-4 shadow-xl"><Sparkles size={18} className="mb-3 text-gold" /><p className="text-sm font-semibold leading-5 text-navy">Small steps create big change.</p></div></div></section>
    <section id="why" className="bg-navy py-20 text-white lg:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.24em] text-gold">A clearer starting point</p><h2 className="mt-4 max-w-2xl text-balance font-serif text-4xl leading-tight sm:text-5xl">Move from concern to understanding.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">The right support often starts with a shared language. We make it easier to talk about what a child needs, what gets in the way and what could help.</p><div className="mt-12 grid gap-4 md:grid-cols-3">{audiences.map(([title, text, Icon]) => <article key={title} className="rounded-2xl border border-white/15 bg-white/[.06] p-6"><Icon className="text-teal" size={24} /><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p><a href="#contact" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold">Find your next step <ArrowRight size={15} /></a></article>)}</div></div></section>
    <section id="pathway" className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-teal">The NeuroPathway approach</p><h2 className="mt-4 max-w-xl text-balance font-serif text-4xl leading-tight text-navy sm:text-5xl">A practical pathway for early action.</h2></div><p className="max-w-sm leading-7 text-muted-foreground">No labels. No shortcuts. Just a more useful way to understand the whole child.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{pathway.map(([label, title, text, Icon], i) => <article key={label} className="border-t-2 border-border pt-6"><div className="mb-10 flex h-12 w-12 items-center justify-center rounded-2xl bg-teal/15 text-teal"><Icon size={22} /></div><p className="text-xs font-bold uppercase tracking-[.2em] text-muted-foreground">{label}</p><h3 className="mt-3 text-2xl font-semibold text-navy">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p><span className="float-right font-serif text-5xl text-navy/10">0{i + 1}</span></article>)}</div></section>
    <section id="about" className="border-y border-border bg-sand py-20 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-teal">Our promise</p><h2 className="mt-4 text-balance font-serif text-4xl leading-tight text-navy sm:text-5xl">Needs first, not labels.</h2></div><div className="grid gap-8 sm:grid-cols-2">{[['Evidence over assumption','We stay close to what has actually been observed: frequency, triggers, impact and the support already tried.'],['Compassion with clarity','We hold strengths alongside needs, so conversations feel constructive rather than judgemental.'],['Shared responsibility','Parents, schools and professionals can work from the same picture and take small steps together.'],['Safeguarding first','Immediate concerns are never minimised. Urgent safeguarding review always takes priority.']].map(([title,text]) => <div key={title}><h3 className="font-semibold text-navy">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-6 py-20 lg:py-24"><p className="text-center text-xs font-bold uppercase tracking-[.24em] text-teal">Questions, answered</p><h2 className="mt-4 text-center font-serif text-4xl text-navy sm:text-5xl">A safe place to begin.</h2><div className="mt-10 divide-y divide-border border-y border-border">{faqs.map(([q,a],i) => <div key={q}><button className="flex w-full items-center justify-between gap-6 py-5 text-left font-semibold text-navy" onClick={() => setFaq(faq === i ? null : i)} aria-expanded={faq === i}><span>{q}</span><ChevronDown size={19} className={faq === i ? 'rotate-180' : ''} /></button>{faq === i && <p className="pb-5 pr-10 leading-7 text-muted-foreground">{a}</p>}</div>)}</div></section>
    <section id="contact" className="bg-teal py-16 text-white lg:py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-6 md:flex-row md:items-center lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-white/70">Ready to take the next step?</p><h2 className="mt-3 max-w-xl text-balance font-serif text-4xl leading-tight sm:text-5xl">Let&apos;s make early understanding possible.</h2></div><a href="mailto:hello@socialinnovationcic.org" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-semibold text-navy">Start a conversation <ArrowRight size={17} /></a></div></section><footer className="bg-navy py-8 text-sm text-white/60"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-6 sm:flex-row sm:justify-between lg:px-10"><p>© {new Date().getFullYear()} Social Innovation CIC</p><p>Every child deserves early understanding and support.</p></div></footer>
  </main>
}

